# Generated by Django 5.2.8 on 2025-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_publication_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='json_crossref',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
