# Generated by Django 5.2.8 on 2025-11-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_publication_json_crossref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='json_crossref',
            new_name='crossref_json',
        ),
    ]
