# Generated by Django 5.2.8 on 2025-11-22 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_rename_json_crossref_publication_crossref_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='reference_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
