# Generated by Django 5.2.8 on 2025-11-23 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_publication_reference_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('orcid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AuthorPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.publication')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('publication', 'author')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='publications', through='references.AuthorPublication', to='references.author'),
        ),
    ]
