# Generated by Django 5.2.8 on 2025-11-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_author_alter_publication_reference_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_key', models.PositiveIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_references', to='references.publication')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_references', to='references.publication')),
            ],
            options={
                'ordering': ['ref_key'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='references',
            field=models.ManyToManyField(related_name='cited_by', through='references.PublicationReference', to='references.publication'),
        ),
    ]
