# Generated by Django 5.2.8 on 2025-11-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_userpublication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='reference_level',
        ),
        migrations.AddField(
            model_name='publication',
            name='parse_references',
            field=models.BooleanField(default=True),
        ),
    ]
